### ISSUE TITLE
compile and test

### ISSUE THREAD

**Issue by zjin-lcf** [DmitryLyakh/hipTT#1]
I was just curious to build and run your library. I built the library with the following changes:

1.  change 3.9.0 to 3.9.1
2.  replace g++ with hipcc because there were errors using g++
```
g++ -o bin/cutt_test -L/opt/rocm-3.9.1/lib/ -lamdhip64 build/cutt_test.o build/TensorTester.o build/CudaMem.o build/CudaUtils.o build/cuttTimer.o -Llib -lcutt -fPIC
/usr/bin/ld: build/TensorTester.o: relocation R_X86_64_32 against symbol `_Z42__device_stub__setTensorCheckPatternKernelPjj' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: build/CudaUtils.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: lib/libcutt.a(cuttkernel.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: lib/libcutt.a(cuttGpuModelKernel.o): relocation R_X86_64_32 against symbol `_Z32__device_stub__runCountersKernelPKiiiiPiS1_S1_' can not be used when making a PIE object; recompile with -fPIE
``` 

Running the test shows the following message
```
TensorTester::checkTranspose FAIL at 98 ref 130 data 40
Test 1 failed
```

For the benchmark, please suggest the options for meaningful results.  Thanks.
```
./bin/cutt_bench
Using Vega 20 [Radeon VII] SM version 9.0
L2 0.00MB
CPU using vector type AVX2 of length 8
0.00 GB/s
0.00 GB/s
0.00 GB/s
0.00 GB/s
scalarCopy 0.000000 GB/s
0.00 GB/s
0.00 GB/s
0.00 GB/s
0.00 GB/s
vectorCopy 0.000000 GB/s
0.00 GB/s
0.00 GB/s
0.00 GB/s
0.00 GB/s
memcpyFloat 0.000000 GB/s
bench OK
seed 1606747073
```

**Comment by DmitryLyakh** [comment]
hipTT is a HIP port of the cuTT library:
https://github.com/DmitryLyakh/cutt
It does not work on AMD yet because the original CUDA code has a lot of places assuming warpSize=32, which needs to be fixed. It only works for CUDA (NVIDIA GPU) as of now.

**Comment by zjin-lcf** [comment]
Before closing it immediately,  could you specify the options for meaningful results for the benchmark on an Nvidia GPU ?

**Comment by DmitryLyakh** [comment]
For NVIDIA GPU you should use the cuTT library directly. The options are given in src/cutt_bench.cpp:
printf("cutt_bench [options]\n");
    printf("Options:\n");
    printf("-device [int]    : GPU ID (default is 0)\n");
    printf("-measure         : use cuttPlanMeasure (default is cuttPlan)\n");
    printf("-plantimer       : planning is timed (default is no)\n");
    printf("-seed [int]      : seed value for random number generator (default is system timer)\n");
    printf("-elemsize [int]  : size of elements in bytes, 4 or 8. (default is 8)\n");
    printf("-dim ...         : space-separated list of dimensions\n");
    printf("-permutation ... : space-separated list of permutations\n");
    printf("-bench benchID   : benchmark to run\n");

**Comment by DmitryLyakh** [comment]
Just in case, before cutt_bench, you should run cutt_test first.
